# Generated by Django 4.2 on 2024-10-15 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email клиента')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия клиента')),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество клиента')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата добавления клиента')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь рассылок')),
            ],
            options={
                'verbose_name': 'клиент для рассылки',
                'verbose_name_plural': 'клиенты для рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тема сообщения')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь рассылок')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время отправки первой рассылки')),
                ('period', models.CharField(choices=[('once', 'Единоразовая рассылка'), ('days', 'Ежедневная рассылка'), ('weeks', 'Еженедельная рассылка'), ('months', 'Ежемесячная рассылка')], verbose_name='Статус рассылки')),
                ('status', models.CharField(choices=[('created', 'Рассылка создана'), ('active', 'Рассылка запущена'), ('closed', 'Рассылка завершена')], verbose_name='Статус рассылки')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания рассылки')),
                ('clients', models.ManyToManyField(related_name='clients', to='newsletters.client', verbose_name='Клиент для рассылки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletters.message', verbose_name='Сообщение для рассылки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь рассылок')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='NewsletterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Дата и время попытки рассылки')),
                ('is_success', models.BooleanField(verbose_name='Попытка успешная')),
                ('report', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчет в случае ошибки попытки')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletters.newsletter', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'попытка рассылки',
                'verbose_name_plural': 'попытки рассылки',
            },
        ),
    ]
