# Generated by Django 4.2 on 2024-10-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'сообщение для рассылки', 'verbose_name_plural': 'сообщения для рассылки'},
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='period',
            field=models.CharField(choices=[('once', 'Единоразовая рассылка'), ('days', 'Ежедневная рассылка'), ('weeks', 'Еженедельная рассылка'), ('months', 'Ежемесячная рассылка')], verbose_name='Периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('created', 'Рассылка создана'), ('active', 'Рассылка запущена'), ('closed', 'Рассылка завершена')], default='created', verbose_name='Статус рассылки'),
        ),
    ]
