# Generated by Django 4.2 on 2024-10-18 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_alter_newsletter_options_alter_message_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('view_owner_newsletter', 'Can view others owner newsletters'), ('set_closed_newsletter', 'Can set closed newsletters')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
