# Generated by Django 4.2 on 2024-10-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0004_alter_newsletter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterreport',
            name='next_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время следующей попытки рассылки'),
        ),
    ]
